import Project1 from '../../../public/images/pdemo1.jpg';
import Project2 from '../../../public/images/pdemo2.jpg';
import Project3 from '../../../public/images/pdemo3.jpg';
import Project4 from '../../../public/images/pdemo4.jpg';
import Project5 from '../../../public/images/pdemo5.jpg';

const projectsData = [
  {
    _id: '1',
    userId: 'user1',
    title: 'Modern Living Room Design',
    name: 'Modern Living Room',
    description:
      'A luxurious modern living room design with minimalistic aesthetics and elegant furniture.',
    category: 'Interior Design',
    workingYear: '2023',
    location: 'New York',
    clients: 'Elite Interiors',
    challenges: 'Space optimization and lighting arrangement',
    ideas: 'Use smart lighting and modular furniture to enhance space usability',
    featureImg: {
      _id: 'img1',
      mimeType: 'image/jpeg',
      fileType: 'jpg',
      size: 500,
      originalName: 'pdemo1.jpg',
      key: 'pdemo1',
      url: Project1,
      __v: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    images: [],
    relatedProjects: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: '2',
    userId: 'user1',
    title: 'Luxury Bedroom Setup',
    name: 'Luxury Bedroom',
    description: 'A cozy and luxurious bedroom setup with premium materials and ambient lighting.',
    category: 'Interior Design',
    workingYear: '2022',
    location: 'San Francisco',
    clients: 'Dream Interiors',
    challenges: 'Balancing comfort and aesthetics',
    ideas: 'Use warm colors and layered textures for a plush feel',
    featureImg: {
      _id: 'img2',
      mimeType: 'image/jpeg',
      fileType: 'jpg',
      size: 520,
      originalName: 'pdemo2.jpg',
      key: 'pdemo2',
      url: Project2,
      __v: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    images: [],
    relatedProjects: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: '3',
    userId: 'user1',
    title: 'Minimalist Kitchen Design',
    name: 'Minimalist Kitchen',
    description: 'A sleek and space-efficient kitchen design with high-quality finishes.',
    category: 'Interior Design',
    workingYear: '2021',
    location: 'Berlin',
    clients: 'Kitchen Masters',
    challenges: 'Maximizing storage without clutter',
    ideas: 'Use smart storage solutions and neutral color palettes',
    featureImg: {
      _id: 'img3',
      mimeType: 'image/jpeg',
      fileType: 'jpg',
      size: 480,
      originalName: 'pdemo3.jpg',
      key: 'pdemo3',
      url: Project3,
      __v: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    images: [],
    relatedProjects: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: '4',
    userId: 'user1',
    title: 'Elegant Office Space',
    name: 'Elegant Office',
    description: 'A professional and elegant office space designed for productivity and comfort.',
    category: 'Interior Design',
    workingYear: '2020',
    location: 'London',
    clients: 'Corporate Interiors',
    challenges: 'Creating a balance between formality and creativity',
    ideas: 'Use ergonomic furniture and modern decor',
    featureImg: {
      _id: 'img4',
      mimeType: 'image/jpeg',
      fileType: 'jpg',
      size: 530,
      originalName: 'pdemo4.jpg',
      key: 'pdemo4',
      url: Project4,
      __v: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    images: [],
    relatedProjects: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
  {
    _id: '5',
    userId: 'user1',
    title: 'Classic Dining Room',
    name: 'Classic Dining',
    description: 'A timeless dining room with a mix of traditional and contemporary elements.',
    category: 'Interior Design',
    workingYear: '2019',
    location: 'Tokyo',
    clients: 'Fine Dining Spaces',
    challenges: 'Blending vintage and modern aesthetics',
    ideas: 'Use classic wood furniture with modern lighting fixtures',
    featureImg: {
      _id: 'img5',
      mimeType: 'image/jpeg',
      fileType: 'jpg',
      size: 550,
      originalName: 'pdemo5.jpg',
      key: 'pdemo5',
      url: Project5,
      __v: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    images: [],
    relatedProjects: [],
    createdAt: new Date(),
    updatedAt: new Date(),
    __v: 0,
  },
];

export default projectsData;
